users:
  asdb:
    username: asdb
    articleIds:
      - 1
    commentIds: []
  mdol:
    username: mdol
    articleIds:
      - 2
    commentIds:
      - 1
  sdfsdf:
    username: sdfsdf
    articleIds:
      - 3
    commentIds:
      - 3
articles:
  '1':
    id: 1
    title: bad
    url: 'http://www.google.com'
    username: asdb
    commentIds: []
    upvotedBy: []
    downvotedBy: []
    comments: []
  '2':
    id: 2
    title: Title
    url: 'http://google.com'
    username: mdol
    commentIds:
      - 1
    upvotedBy: []
    downvotedBy:
      - mdol
    comments:
      - &ref_0
        id: 1
        body: Hi
        username: mdol
        articleId: 2
        upvotedBy: []
        downvotedBy: []
  '3':
    id: 3
    title: qweqwe
    url: qweqwe
    username: sdfsdf
    commentIds:
      - 3
    upvotedBy: []
    downvotedBy: []
    comments:
      - &ref_1
        id: 3
        body: |
          Nice post
        username: sdfsdf
        articleId: 3
        upvotedBy: []
        downvotedBy: []
nextArticleId: 4
comments:
  '1': *ref_0
  '2': null
  '3': *ref_1
nextCommentId: 4
